### ISSUE TITLE
你这项目都跑不起来，跟直播分享出来的链接完全是两个版本

### ISSUE THREAD

**Issue by oEstate** [polyv/live-js-sdk-demo-normal#5]
能提供最新代码吗

**Comment by heeroluo** [comment]
您好，跑不起来报的错误信息是缺少 swiper 这个依赖吗？如果 Node.js 是 16 以下的版本，会出现这个问题。我们会做一下兼容。
另外，直播分享出来的链接是指哪个链接呢？

**Comment by oEstate** [comment]
https://live.polyv.cn/watch/3447557




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年11月8日(星期二) 上午10:43
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [polyv/live-js-sdk-demo-normal] 你这项目都跑不起来，跟直播分享出来的链接完全是两个版本 (Issue #5)





 
您好，跑不起来报的错误信息是缺少 swiper 这个依赖吗？如果 Node.js 是 16 以下的版本，会出现这个问题。我们会做一下兼容。
 另外，直播分享出来的链接是指哪个链接呢？

**Comment by heeroluo** [comment]
您好，这个 demo 的功能确实跟 https://live.polyv.cn/watch/3447557 是不一致的。如果因为功能缺失导致无法满足您的需求，可以跟我们的售后或者 SDK 的对接人员提出。

**Comment by heeroluo** [comment]
已经增加 swiper 这个依赖，目前项目在 Node.js 12 也能跑起来了。
